export const drivers2025 = [
  { id: 1, name: "Max Verstappen", team: "Red Bull Racing", number: 1, country: "Netherlands", countryFlag: "🇳🇱" },
  { id: 2, name: "Liam Lawson", team: "Red Bull Racing", number: 30, country: "New Zealand", countryFlag: "🇳🇿" },
  { id: 3, name: "Lewis Hamilton", team: "Ferrari", number: 44, country: "United Kingdom", countryFlag: "🇬🇧" },
  { id: 4, name: "Charles Leclerc", team: "Ferrari", number: 16, country: "Monaco", countryFlag: "🇲🇨" },
  { id: 5, name: "Lando Norris", team: "McLaren", number: 4, country: "United Kingdom", countryFlag: "🇬🇧" },
  { id: 6, name: "Oscar Piastri", team: "McLaren", number: 81, country: "Australia", countryFlag: "🇦🇺" },
  { id: 7, name: "George Russell", team: "Mercedes", number: 63, country: "United Kingdom", countryFlag: "🇬🇧" },
  { id: 8, name: "Andrea Kimi Antonelli", team: "Mercedes", number: 12, country: "Italy", countryFlag: "🇮🇹" },
  { id: 9, name: "Fernando Alonso", team: "Aston Martin", number: 14, country: "Spain", countryFlag: "🇪🇸" },
  { id: 10, name: "Lance Stroll", team: "Aston Martin", number: 18, country: "Canada", countryFlag: "🇨🇦" },
  { id: 11, name: "Pierre Gasly", team: "Alpine", number: 10, country: "France", countryFlag: "🇫🇷" },
  { id: 12, name: "Jack Doohan", team: "Alpine", number: 7, country: "Australia", countryFlag: "🇦🇺" },
  { id: 13, name: "Yuki Tsunoda", team: "Racing Bulls", number: 22, country: "Japan", countryFlag: "🇯🇵" },
  { id: 14, name: "Isack Hadjar", team: "Racing Bulls", number: 6, country: "France", countryFlag: "🇫🇷" },
  { id: 15, name: "Nico Hulkenberg", team: "Sauber", number: 27, country: "Germany", countryFlag: "🇩🇪" },
  { id: 16, name: "Gabriel Bortoleto", team: "Sauber", number: 5, country: "Brazil", countryFlag: "🇧🇷" },
  { id: 17, name: "Esteban Ocon", team: "Haas", number: 31, country: "France", countryFlag: "🇫🇷" },
  { id: 18, name: "Oliver Bearman", team: "Haas", number: 87, country: "United Kingdom", countryFlag: "🇬🇧" },
  { id: 19, name: "Alexander Albon", team: "Williams", number: 23, country: "Thailand", countryFlag: "🇹🇭" },
  { id: 20, name: "Carlos Sainz", team: "Williams", number: 55, country: "Spain", countryFlag: "🇪🇸" },
];
