export const ROUTE_PATHS = {
  ROOT: "/",
  LANDING: "/landing",
  ADMIN_LOGIN: "/admin",
  ADMIN_DASHBOARD: "/AdminDashboard",
  ADMIN_DASHBOARD_MINISTORE: "/AdminDashboard/ministore",
  ADMIN_DASHBOARD_MINISTORE_USERS: "/AdminDashboard/ministore/users",
  ADMIN_DASHBOARD_MINISTORE_PRODUCTS: "/AdminDashboard/ministore/products",
  ADMIN_DASHBOARD_MINISTORE_DISCOUNTS: "/AdminDashboard/ministore/discounts",
  ADMIN_DASHBOARD_MINISTORE_BILLINGS: "/AdminDashboard/ministore/billings",
  ADMIN_DASHBOARD_MINISTORE_ORDERS: "/AdminDashboard/ministore/orders",
  ADMIN_DASHBOARD_MINISTORE_CARTS: "/AdminDashboard/ministore/carts",
  LOGIN: "/login",
  SIGNUP: "/signup",
  FORGOT_PASSWORD: "/forgotpass",
  TEAMS: "/teams",
  TEAM_DETAIL: "/teams/:id",
  DRIVERS: "/drivers",
  DRIVER_DETAIL: "/drivers/:id",
  CALENDAR: "/calendar",
  CALENDAR_DETAIL: "/calendar/:id",
  CIRCUITS: "/circuits",
  CIRCUIT_DETAIL: "/circuits/:id",
  STORE: "/store",
  MINI_STORE: "/store",
  ACCOUNT: "/account",
};
