const PLACEHOLDER_IMAGE =
  "https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=800&auto=format";

export const races = [
  {
    id: "bahrain",
    round: 1,
    name: "Bahrain Grand Prix",
    date: "March 2, 2026",
    location: "Sakhir, Bahrain",
    circuit: "Bahrain International Circuit",
    laps: 57,
    distance: "308.238 km",
    lapRecord: "1:31.447 (Pedro de la Rosa, 2005)",
    image: PLACEHOLDER_IMAGE,
  },
  {
    id: "saudi",
    round: 2,
    name: "Saudi Arabian Grand Prix",
    date: "March 9, 2026",
    location: "Jeddah, Saudi Arabia",
    circuit: "Jeddah Corniche Circuit",
    laps: 50,
    distance: "308.450 km",
    lapRecord: "1:30.734 (Lewis Hamilton, 2021)",
    image: PLACEHOLDER_IMAGE,
  },
  {
    id: "australia",
    round: 3,
    name: "Australian Grand Prix",
    date: "March 23, 2026",
    location: "Melbourne, Australia",
    circuit: "Albert Park Circuit",
    laps: 58,
    distance: "306.124 km",
    lapRecord: "1:20.260 (Charles Leclerc, 2024)",
    image: PLACEHOLDER_IMAGE,
  },
  {
    id: "japan",
    round: 4,
    name: "Japanese Grand Prix",
    date: "April 6, 2026",
    location: "Suzuka, Japan",
    circuit: "Suzuka International Racing Course",
    laps: 53,
    distance: "307.471 km",
    lapRecord: "1:30.983 (Lewis Hamilton, 2019)",
    image: PLACEHOLDER_IMAGE,
  },
  {
    id: "china",
    round: 5,
    name: "Chinese Grand Prix",
    date: "April 20, 2026",
    location: "Shanghai, China",
    circuit: "Shanghai International Circuit",
    laps: 56,
    distance: "305.066 km",
    lapRecord: "1:32.238 (Michael Schumacher, 2004)",
    image: PLACEHOLDER_IMAGE,
  },
  {
    id: "miami",
    round: 6,
    name: "Miami Grand Prix",
    date: "May 4, 2026",
    location: "Miami, USA",
    circuit: "Miami International Autodrome",
    laps: 57,
    distance: "308.326 km",
    lapRecord: "1:29.708 (Max Verstappen, 2023)",
    image: PLACEHOLDER_IMAGE,
  },
  {
    id: "emilia-romagna",
    round: 7,
    name: "Emilia Romagna Grand Prix",
    date: "May 18, 2026",
    location: "Imola, Italy",
    circuit: "Autodromo Enzo e Dino Ferrari",
    laps: 63,
    distance: "309.049 km",
    lapRecord: "1:15.484 (Lewis Hamilton, 2020)",
    image: PLACEHOLDER_IMAGE,
  },
  {
    id: "monaco",
    round: 8,
    name: "Monaco Grand Prix",
    date: "May 25, 2026",
    location: "Monte Carlo, Monaco",
    circuit: "Circuit de Monaco",
    laps: 78,
    distance: "260.286 km",
    lapRecord: "1:12.909 (Lewis Hamilton, 2021)",
    image: PLACEHOLDER_IMAGE,
  },
  {
    id: "canada",
    round: 9,
    name: "Canadian Grand Prix",
    date: "June 8, 2026",
    location: "Montreal, Canada",
    circuit: "Circuit Gilles Villeneuve",
    laps: 70,
    distance: "305.270 km",
    lapRecord: "1:13.078 (Valtteri Bottas, 2019)",
    image: PLACEHOLDER_IMAGE,
  },
  {
    id: "spain",
    round: 10,
    name: "Spanish Grand Prix",
    date: "June 22, 2026",
    location: "Barcelona, Spain",
    circuit: "Circuit de Barcelona-Catalunya",
    laps: 66,
    distance: "307.236 km",
    lapRecord: "1:18.149 (Max Verstappen, 2023)",
    image: PLACEHOLDER_IMAGE,
  },
  {
    id: "austria",
    round: 11,
    name: "Austrian Grand Prix",
    date: "June 29, 2026",
    location: "Spielberg, Austria",
    circuit: "Red Bull Ring",
    laps: 71,
    distance: "306.452 km",
    lapRecord: "1:05.619 (Carlos Sainz, 2020)",
    image: PLACEHOLDER_IMAGE,
  },
  {
    id: "britain",
    round: 12,
    name: "British Grand Prix",
    date: "July 6, 2026",
    location: "Silverstone, UK",
    circuit: "Silverstone Circuit",
    laps: 52,
    distance: "306.198 km",
    lapRecord: "1:27.097 (Max Verstappen, 2020)",
    image: PLACEHOLDER_IMAGE,
  },
];
